version: "3.7"

networks: 
    mynetwork:
        name: mynetwork
        attachable: true    

services:
    redis:
        image: 'redis:latest'
        container_name: redis_proje_api
        command: redis-server --save 20 1 --loglevel warning --requirepass "9090"
        ports:
            - '6379:6379'
        networks:
            - mynetwork
        volumes:
            - ./Logs/redis:/data
  
    postgres:
        image: postgres:12.0-alpine
        container_name: postgres_proje_api
        volumes:
            - ./postgres_data:/var/lib/postgresql/data
        command: ["postgres", "-c", "log_statement=all"]            
        environment:
            POSTGRES_DB: keycloak
            POSTGRES_USER: keycloak
            POSTGRES_PASSWORD: password
        ports:
            - '5432:5432'
        networks:
            - mynetwork

    keycloak:
        image: jboss/keycloak:16.0.0
        container_name: keycloak_proje_api
        environment:
            DB_VENDOR: POSTGRES
            DB_ADDR: postgres
            DB_DATABASE: keycloak
            DB_USER: keycloak
            DB_SCHEMA: public
            DB_PASSWORD: password
            KEYCLOAK_USER: admin
            KEYCLOAK_PASSWORD: password
        ports:
            - '8443:8443'
        volumes:
            - /etc/nginx/ssl/localhost.crt:/etc/x509/https/tls.crt
            - /etc/nginx/ssl/localhost.key:/etc/x509/https/tls.key
            - ./Logs/keycloak:/opt/jboss/keycloak/standalone/log
        depends_on:
            - postgres
        networks:
            - mynetwork

    relying_party:
        image: nginx_rp:latest
        container_name: nginx_rp_proje_api
        networks:
            - mynetwork    
        depends_on:
            - redis            
        volumes:
            - ./nginx_rp/:/usr/local/openresty/nginx/conf/
            - ./Logs/relying_party:/var/log/nginx              
        ports:
            - '1443:1443'

    app:
        image: nginx:latest
        container_name: nginx_app_proje_api
        networks:
            - mynetwork	    
        volumes:
            - ./nginx_app/config/:/etc/nginx/
            - ./Logs/app:/var/log/nginx              
        command: [nginx-debug, '-g', 'daemon off;']
        ports:
            - '8080:80'

    gateway:
        image: nginx_gateway:latest
        container_name: nginx_gateway_proje_api
        volumes:
            - ./nginx_gateway/:/usr/local/openresty/nginx/conf/
            - ./Logs/gateway:/var/log/nginx  
        depends_on:
            - redis  
            - app                
        networks:
            - mynetwork
        ports:
            - '443:443'            
         
    example_js:
      image: example_nodejs:latest
      container_name: example_nodejs_proje_api
      networks:
            - mynetwork
      ports:
            - '7777:7777'
