version: "3.7"

networks: 
    mynetwork:
        name: mynetwork
        attachable: true    

services:
    redis:
        image: 'redis:latest'
        container_name: redis_proje_api
        command: redis-server --requirepass "9090"
        ports:
        - '6379:6379'
        networks:
        - mynetwork
  
    postgres:
        image: postgres:12.0-alpine
        container_name: postgres_proje_api
        volumes:
            - ./postgres_data:/var/lib/postgresql/data
        environment:
            POSTGRES_DB: keycloak
            POSTGRES_USER: keycloak
            POSTGRES_PASSWORD: password
        ports:
            - '5432:5432'
        networks:
            - mynetwork

    keycloak:
        image: jboss/keycloak:16.0.0
        container_name: keycloak_proje_api
        environment:
            DB_VENDOR: POSTGRES
            DB_ADDR: postgres
            DB_DATABASE: keycloak
            DB_USER: keycloak
            DB_SCHEMA: public
            DB_PASSWORD: password
            KEYCLOAK_USER: admin
            KEYCLOAK_PASSWORD: password
        ports:
            - '8443:8443'
        volumes:
            - /etc/nginx/ssl/localhost.crt:/etc/x509/https/tls.crt
            - /etc/nginx/ssl/localhost.key:/etc/x509/https/tls.key
        depends_on:
            - postgres
        networks:
            - mynetwork

    relying_party:
        image: nginx_rp:latest
        container_name: nginx_rp_proje_api
        networks:
            - mynetwork    
        ports:
            - '1443:1443'

    gateway:
        image: nginx_gateway:latest
        container_name: nginx_gateway_proje_api
        networks:
            - mynetwork
        ports:
            - '443:443'            
